### ISSUE TITLE
Build error on MAC - unresolved dependency: com.thenewmotion.akka#akka-rabbitmq_2.11;2.2: not found

### ISSUE THREAD

**Issue by vagarwal77** [deepsense-ai/seahorse#102]
i am getting - sbt.ResolveException: unresolved dependency: com.thenewmotion.akka#akka-rabbitmq_2.11;2.2: not found

--- 
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.typesafe.akka:akka-actor_2.11:2.3.14 -> 2.4.9
[warn] Run 'evicted' to see detailed eviction warnings
[info] Resolving com.thenewmotion.akka#akka-rabbitmq_2.11;2.2 ...
[warn] 	module not found: com.thenewmotion.akka#akka-rabbitmq_2.11;2.2
[warn] ==== local: tried
[warn]   /Users/vivekagarwal/.ivy2/local/com.thenewmotion.akka/akka-rabbitmq_2.11/2.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/thenewmotion/akka/akka-rabbitmq_2.11/2.2/akka-rabbitmq_2.11-2.2.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/vivekagarwal/.sbt/preloaded/com.thenewmotion.akka/akka-rabbitmq_2.11/2.2/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/vivekagarwal/.sbt/preloaded/com/thenewmotion/akka/akka-rabbitmq_2.11/2.2/akka-rabbitmq_2.11-2.2.pom
[warn] ==== typesafe.com: tried
[warn]   http://repo.typesafe.com/typesafe/repo/com/thenewmotion/akka/akka-rabbitmq_2.11/2.2/akka-rabbitmq_2.11-2.2.pom
[warn] ==== sonatype.org: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/thenewmotion/akka/akka-rabbitmq_2.11/2.2/akka-rabbitmq_2.11-2.2.pom
[warn] ==== spray.io: tried
[warn]   http://repo.spray.io/com/thenewmotion/akka/akka-rabbitmq_2.11/2.2/akka-rabbitmq_2.11-2.2.pom
[warn] ==== The New Motion Public Repo: tried
[warn]   http://nexus.thenewmotion.com/content/groups/public/com/thenewmotion/akka/akka-rabbitmq_2.11/2.2/akka-rabbitmq_2.11-2.2.pom
[warn] ==== central.maven.org: tried
[warn]   http://central.maven.org/maven2/com/thenewmotion/akka/akka-rabbitmq_2.11/2.2/akka-rabbitmq_2.11-2.2.pom
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.thenewmotion.akka#akka-rabbitmq_2.11;2.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.thenewmotion.akka:akka-rabbitmq_2.11:2.2 (/Users/vivekagarwal/code-repo/seahorse/seahorse-workflow-executor/workflowexecutormqprotocol/build.sbt#L19-20)
[warn] 		  +- ai.deepsense:seahorse-executor-workflowexecutor-mq-protocol_2.11:1.4.4-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.thenewmotion.akka#akka-rabbitmq_2.11;2.2: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1488)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1484)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1519)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1517)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1522)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1516)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1539)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1466)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1418)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] ({file:/Users/vivekagarwal/code-repo/seahorse/seahorse-workflow-executor/}workflowexecutormqprotocol/*:update) sbt.ResolveException: unresolved dependency: com.thenewmotion.akka#akka-rabbitmq_2.11;2.2: not found
[error] Total time: 80 s, completed Mar 18, 2019 7:31:50 PM
Traceback (most recent call last):
  File "./build/manage-docker.py", line 151, in <module>
    main()
  File "./build/manage-docker.py", line 125, in main
    build_dockers(selected_confs)
  File "./build/manage-docker.py", line 140, in build_dockers
    subprocess.check_call(final_sbt_command, shell=True, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '(find . -name target -type d -exec rm -rf {} \; || true) && sbt clean &&sbt -DSPARK_VERSION=2.1.1 schedulingmanager/docker sessionmanager/docker workflowmanager/docker datasourcemanager/docker libraryservice/docker' returned non-zero exit status 1
Vivek-Agarwals-MacBook-Pro:seahorse vivekagarwal$

**Comment by ilyakitaev** [comment]
Changes I've made to build projects

`
diff --git a/deployment/authorization-docker/Dockerfile b/deployment/authorization-docker/Dockerfile
index 31ef587b8..381c00453 100644
--- a/deployment/authorization-docker/Dockerfile
+++ b/deployment/authorization-docker/Dockerfile
@@ -3,9 +3,10 @@ FROM hortonworks/cloudbreak-uaa:3.6.0
 
 ENV H2_VERSION 1.4.192
 
+RUN echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" >  /etc/apt/sources.list.d/jessie-backports.list
 # build-essential gcc ruby-dev rubygems libssl-dev packages are needed by cf-uaac
 # get moreutils for sponge
-RUN apt-get update && \
+RUN apt-get -o Acquire::Check-Valid-Until=false update && \
     DEBIAN_FRONTEND=noninteractive apt-get install -y ruby ruby-dev rubygems mailutils build-essential openssl zip && \
     gem install cf-uaac && \
     apt-get install -y moreutils && \
diff --git a/seahorse-workflow-executor/project/Dependencies.scala b/seahorse-workflow-executor/project/Dependencies.scala
index 31243e458..035353cf3 100644
--- a/seahorse-workflow-executor/project/Dependencies.scala
+++ b/seahorse-workflow-executor/project/Dependencies.scala
@@ -51,6 +51,8 @@ object Library {
   val spark = (name: String) => (version: String) => "org.apache.spark" %% s"spark-$name" % version excludeScalatest
   val spray = (name: String) => "io.spray" %% s"spray-$name" % Version.spray excludeAkkaActor
 
+  val annotations = "javax.annotation" % "javax.annotation-api" % "1.3.2"
+
   val akkaActor = akka("actor")
   val akkaTestkit = akka("testkit")
   val amazonS3 = "com.amazonaws" % "aws-java-sdk-s3" % Version.amazonS3 excludeJackson
@@ -63,7 +65,7 @@ object Library {
   val log4JExtras = "log4j" % "apache-log4j-extras" % "1.2.17"
   val nscalaTime = "com.github.nscala-time" %% "nscala-time" % Version.nsscalaTime
   val mockitoCore = "org.mockito" % "mockito-core" % Version.mockito
-  val rabbitmq = "com.thenewmotion.akka" %% "akka-rabbitmq" % "2.2" excludeAkkaActor
+  val rabbitmq = "com.thenewmotion" %% "akka-rabbitmq" % "3.0.0" excludeAkkaActor
   val reflections = "org.reflections" % "reflections" % "0.9.11"
   val scalacheck = "org.scalacheck" %% "scalacheck" % Version.scalacheck
   val scalate = "org.scalatra.scalate" %% "scalate-core" % "1.7.1"
@@ -148,7 +150,8 @@ object Dependencies {
   val api = retrofit ++ Seq(
     oauth2Client,
     swaggerAnnotations,
-    jodaTime
+    jodaTime,
+    annotations
   )
 
   val commons = usedSpark.onlyInTests ++ Seq(

`
