### ISSUE TITLE
Adding custom operation assembly to `jars` dir generates volumes of Reflections execeptions

### ISSUE THREAD

**Issue by metasim** [deepsense-ai/seahorse#11]
I have a very simple `DOperation0To1` operation defined in this project:

https://github.com/metasim/seahorse-test

I build it with `sbt assembly` and copy the resulting `jar` file to the `seahorse/jars` directory.

While it operates fine once everything is running, it generates 10s of thousands of lines of exception backtraces from the `Reflections` library. They generally report that some class couldn't be found in `org.reflections.Reflections.expandSuperTypes`, even though that class has to have been available for the workflow to have worked. This makes me think it's a `ClassLoader` configuration issue in `Reflections.

The exceptions appear to only be generated when the operation has external dependencies. If I just install the `IdentityOperation` things are fine.

While that fact that my operations still work means this bug isn't critical, it definitely slows down startup time and makes finding startup errors more difficult

Note: If pointed in the right direction, I'd be happy to take a stab at fixing this.

**Comment by metasim** [comment]
Here's an example backtrace. There are hundreds + of these generated at startup and when `spark-submit` is invoked.

```
[WARN ] [2018-02-12 21:29:59,601] [main]  org.reflections.Reflections - could not get type for name shaded.org.apache.http.client.ResponseHandler from any class loader
org.reflections.ReflectionsException: could not get type for name shaded.org.apache.http.client.ResponseHandler
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at ai.deepsense.deeplang.refl.CatalogScanner.scanForRegistrables(CatalogScanner.scala:73)
	at ai.deepsense.deeplang.refl.CatalogScanner.scanAndRegister(CatalogScanner.scala:52)
	at ai.deepsense.deeplang.CatalogRecorder.catalogs$lzycompute(CatalogRecorder.scala:269)
	at ai.deepsense.deeplang.CatalogRecorder.catalogs(CatalogRecorder.scala:265)
	at ai.deepsense.workflowmanager.deeplang.DeepLangModule.provideDOperationsCatalog(DeepLangModule.scala:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:104)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:89)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:98)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:83)
	at ai.deepsense.workflowmanager.WorkflowManagerApp$.delayedEndpoint$ai$deepsense$workflowmanager$WorkflowManagerApp$1(WorkflowManagerApp.scala:44)
	at ai.deepsense.workflowmanager.WorkflowManagerApp$delayedInit$body.apply(WorkflowManagerApp.scala:37)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at ai.deepsense.workflowmanager.WorkflowManagerApp$.main(WorkflowManagerApp.scala:37)
	at ai.deepsense.workflowmanager.WorkflowManagerApp.main(WorkflowManagerApp.scala)
Caused by: java.lang.ClassNotFoundException: shaded.org.apache.http.client.ResponseHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
	... 48 more
```

**Comment by metasim** [comment]
FWIW: I changed this line:

https://github.com/deepsense-ai/seahorse/blob/dcc0094c85e7ceb7a5f7d26cc9c7baeb8f77a500/seahorse-workflow-executor/deeplang/src/main/scala/ai/deepsense/deeplang/refl/CatalogScanner.scala#L67

to be

```scala
val configBuilder = ConfigurationBuilder.build(urls.toSeq: _*).setExpandSuperTypes(false)
```

and the errors went away. My custom operation still worked, but I don't know what the down stream implications of this change might be, nor how I might test it, so I'm not comfortable submitting a PR for it without further guidance.

**Comment by jaroslaw-osmanski** [comment]
Thanks for pointing this warnings out. I think ideally we want fix the root cause for this warning and I have a feeling that setExpandSuperTypes(false) might make debugging harder by removing information from logs. This is why we won't merge your fix at this time.

We are very open to PR. Use `sbt scalastylebackend`. To run tests: ./build/build_and_run_tests.sh. 
We'll do this anyway for accepting PR but that will speed up accepting changes.

**Comment by metasim** [comment]
@jaroslaw-osmanski A follow up to this (I may be splitting hairs here):

> Thanks for pointing this warnings out. I think ideally we want fix the root cause for this warning and I have a feeling that setExpandSuperTypes(false) might make debugging harder by removing information from logs. This is why we won't merge your fix at this time.

The `setExpandSuperTypes` call doesn't actually effect logging; it keeps the _Reflections_ library from running up the inheritance chain unnecessarily. That said, I actually think there's another bug [somewhere in here](https://github.com/deepsense-ai/seahorse/blob/dcc0094c85e7ceb7a5f7d26cc9c7baeb8f77a500/seahorse-workflow-executor/deeplang/src/main/scala/ai/deepsense/deeplang/refl/CatalogScanner.scala#L63-L73) where some `ClassLoader` boundary being accidentally imposed on _Reflections_, but only in the case of custom operations in the `seahorse/jars` directory. But that's just a gut theory.

**Comment by metasim** [comment]
Current suspicion about this is that it's caused by this bug in _Reflections_

https://github.com/ronmamo/reflections/issues/190

**Comment by metasim** [comment]
Another possibility is that this is caused by the parent `ClassLoader` not being used in instantiating the `URLClassLoader`. I think this call:

https://github.com/deepsense-ai/seahorse/blob/c1b2e6643b7117b08cb326f396d187c302368f2c/seahorse-workflow-executor/deeplang/src/main/scala/ai/deepsense/deeplang/refl/CatalogScanner.scala#L70

should be changed to:

```scala
URLClassLoader.newInstance(jarsUrls.toArray, getClass.getClassLoader)
```
