### ISSUE TITLE
Error on first-time build: Couldn't find npmrc file "codilime"

### ISSUE THREAD

**Issue by metasim** [deepsense-ai/seahorse#21]
This is a very minor issue.  When performing a build for the first time in a clean environment (new dev environment, `npm` just installed, etc.) the following error is produced. Running the build a second time makes it past this step successfully. Logging it in the event someone else hits up against it.

```
...
>>> Building frontend
+ prepare_environment
+ echo '** Preparing Environment **'
** Preparing Environment **
+ npmrc -c codilime
Initialising npmrc...
Creating /Users/sfitch/.npmrcs
Activating .npmrc "default"
+ npmrc codilime
Couldn't find npmrc file "codilime".
Traceback (most recent call last):
  File "./build/manage-docker.py", line 151, in <module>
    main()
  File "./build/manage-docker.py", line 125, in main
    build_dockers(selected_confs)
  File "./build/manage-docker.py", line 132, in build_dockers
    subprocess.check_call(conf.command, shell=True, cwd=cwd)
  File "/anaconda3/envs/py27/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'frontend/docker/build-frontend.sh' returned non-zero exit status 1
```

**Comment by jaroslaw-osmanski** [comment]
This should be fixed by: https://github.com/deepsense-ai/seahorse/pull/31
