### ISSUE TITLE
password reset goes awry, self-registration too

### ISSUE THREAD

**Issue by JosefAssad** [deepsense-ai/seahorse#3]
I'm running with the docker-compose.yml downloaded from the deepsense website, haven't built from source from this repo yet, so feel free to close this issue if it's known and fixed here.

I've turned authorisation on and switched the admin e-mail to my own as described [here](https://seahorse.deepsense.ai/docs/1.4/reference/server_mode.html).

On the login screeen, I click "reset password". On the password reset screen, I enter the e-mail address which I specified in the docker-compose.yml. I click "Send reset password link".

I get a screen saying "Uh oh. Something went amiss."

docker-compose logs says this when I click the button "Send reset password link":

```
authorization_1      | [2017-09-20 11:26:58.927] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [loginAuthenticateRequestMatcher] Checking match of request : '/authorization/forgot_password.do'; '/authorization/authenticate' with parameters={} and headers {Authorization=[bearer ], accept=[application/json]}
authorization_1      | [2017-09-20 11:26:58.927] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [loginAuthorizeRequestMatcher] Checking match of request : '/authorization/forgot_password.do'; '/authorization/oauth/authorize' with parameters={source=login} and headers {accept=[application/json]}
authorization_1      | [2017-09-20 11:26:58.927] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [loginTokenRequestMatcher] Checking match of request : '/authorization/forgot_password.do'; '/authorization/oauth/token' with parameters={source=login, grant_type=password, add_new=} and headers {Authorization=[bearer ], accept=[application/json]}
authorization_1      | [2017-09-20 11:26:58.928] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [loginAuthorizeRequestMatcherOld] Checking match of request : '/authorization/forgot_password.do'; '/authorization/oauth/authorize' with parameters={login={} and headers {accept=[application/json]}
authorization_1      | [2017-09-20 11:26:58.928] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [passcodeTokenMatcher] Checking match of request : '/authorization/forgot_password.do'; '/authorization/oauth/token' with parameters={grant_type=password, passcode=} and headers {accept=[application/json, application/x-www-form-urlencoded]}
authorization_1      | [2017-09-20 11:26:58.928] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [oauthAuthorizeRequestMatcher] Checking match of request : '/authorization/forgot_password.do'; '/authorization/oauth/authorize' with parameters={response_type=token, source=credentials} and headers {accept=[application/json, application/x-www-form-urlencoded]}
authorization_1      | [2017-09-20 11:26:58.928] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [oauthAuthorizeApiRequestMatcher] Checking match of request : '/authorization/forgot_password.do'; '/authorization/oauth/authorize' with parameters={response_type=code, client_id=} and headers {Authorization=[bearer ]}
authorization_1      | [2017-09-20 11:26:58.928] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [xOauthCallbackRequestMatcher] Checking match of request : '/authorization/forgot_password.do'; '/authorization/login/callback' with parameters={code=} and headers {}
authorization_1      | [2017-09-20 11:26:58.928] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [oauthAuthorizeRequestMatcherOld] Checking match of request : '/authorization/forgot_password.do'; '/authorization/oauth/authorize' with parameters={response_type=token, credentials={} and headers {accept=[application/json, application/x-www-form-urlencoded]}
authorization_1      | [2017-09-20 11:26:58.928] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [autologinAuthorizeRequestMatcher] Checking match of request : '/authorization/forgot_password.do'; '/authorization/oauth/authorize' with parameters={response_type=code, code=} and headers {}
authorization_1      | [2017-09-20 11:26:58.929] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [autologinRequestMatcher] Checking match of request : '/authorization/forgot_password.do'; '/authorization/autologin' with parameters={code=} and headers {}
authorization_1      | [2017-09-20 11:26:58.929] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- CorsFilter: CORS Processing request: URI: /authorization/forgot_password.do; Scheme: http; Host: seahorsedemo.westeurope.cloudapp.azure.com; Port: 33321; Origin: http://seahorsedemo.westeurope.cloudapp.azure.com:33321; Method: POST
authorization_1      | [2017-09-20 11:26:58.929] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- CorsFilter: Request cross origin request has passed validation.
authorization_1      | [2017-09-20 11:26:58.932] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- IdentityZoneResolvingFilter: No root domains configured, UAA is catch-all domain for host:seahorsedemo.westeurope.cloudapp.azure.com
authorization_1      | [2017-09-20 11:26:58.937] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- DisableIdTokenResponseTypeFilter: Processing id_token disable filter
authorization_1      | [2017-09-20 11:26:58.938] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- DisableIdTokenResponseTypeFilter: pre id_token disable:false pathinfo:null request_uri:/authorization/forgot_password.do response_type:null
authorization_1      | [2017-09-20 11:26:58.938] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- DisableIdTokenResponseTypeFilter: post id_token disable:false pathinfo:null request_uri:/authorization/forgot_password.do response_type:null
authorization_1      | [2017-09-20 11:26:58.938] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter: Filter chain 'forgotPasswordSecurity' processing request POST /authorization/forgot_password.do
authorization_1      | [2017-09-20 11:26:58.942] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- JdbcScimUserProvisioning: Filtering groups with SQL: sql: ((LOWER(userName) = LOWER(:__kx1dm9_0) AND LOWER(origin) = LOWER(:__kx1dm9_1)) AND LOWER(identity_zone_id) = LOWER(:__kx1dm9_2)), params: {__kx1dm9_0=jas@2021.ai, __kx1dm9_1=uaa, __kx1dm9_2=uaa}
authorization_1      | [2017-09-20 11:26:58.943] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- JdbcScimUserProvisioning: complete sql: select id,version,created,lastModified,username,email,givenName,familyName,active,phoneNumber,verified,origin,external_id,identity_zone_id,salt,passwd_lastmodified  from users where (((LOWER(userName) = LOWER(:__kx1dm9_0) AND LOWER(origin) = LOWER(:__kx1dm9_1)) AND LOWER(identity_zone_id) = LOWER(:__kx1dm9_2))), params: {__kx1dm9_0=jas@2021.ai, __kx1dm9_1=uaa, __kx1dm9_2=uaa}
authorization_1      | [2017-09-20 11:26:58.954] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- JdbcExpiringCodeStore: Expiring code sweeper complete, deleted 0 entries.
authorization_1      | [2017-09-20 11:26:58.956] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] ....  INFO --- Audit: PasswordResetRequest ('null'): principal=jas@2021.ai, origin=[caller=anonymousUser, details=(org.springframework.security.web.authentication.WebAuthenticationDetails@0: RemoteIpAddress: 10.255.3.5; SessionId: 0D3E93C18196B799C945B613D0D43152)], identityZoneId=[uaa]
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:   nested exception is:
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:  java.net.ConnectException: Connection refused. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:   nested exception is:
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:  java.net.ConnectException: Connection refused; message exceptions (1) are:
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter: Failed message 1: javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:   nested exception is:
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:  java.net.ConnectException: Connection refused
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:  at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:  at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
authorization_1      | [2017-09-20 11:26:58.959] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter:  at org.cloudfoundry.identity.uaa.web.BackwardsCompatibleScopeParsingFilter.doFilter(BackwardsCompatibleScopeParsingFilter.java:40)
```

Etc. etc. Do let me know if you want the full thing.

Am I correct in assuming it's expecting the host to have an available SMTP?

*edit* Turns out, same problem with user self-registration. Appears to be focused on problems with SMTP.

I'm running this in Azure on a Debian Stretch. Is it a port which needs to be opened, maybe?

**Comment by mdsheerazaziz** [comment]
I am getting same error. Did you found any solution?

**Comment by jaroslaw-osmanski** [comment]
Does this still happen in 1.4.2? Host firewall might prevent communication between docker. Check if you can send mail from authorization docker:
```
docker exec -it seahorse_authorization_1 bash
/usr/sbin/sendmail USERNAME@Host
```

You can also check if exim4 is working:
```
service exim4 status
```
