### ISSUE TITLE
socket hangup error while trying to open seahorse

### ISSUE THREAD

**Issue by satya23k** [deepsense-ai/seahorse#4]
I get the following error while trying to open seahorse in browser. Might this be a problem with installation?

`GET /v1/sessions - - ms - -
{ Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketCloseListener (_http_client.js:286:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12) code: 'ECONNRESET' }
`

**Comment by bleachzk** [comment]
I get same error...

**Comment by satya23k** [comment]
executing `docker-compose down ` and then `up` seems to solve the issue for me
