### ISSUE TITLE
Cannot connect to Python gateway

### ISSUE THREAD

**Issue by simone3991** [deepsense-ai/seahorse#70]
Hi! 

I am testing the `seahorse-workflow-executor` app to build a back-end-only engine able to run a json.
Therefore, I generated a simple json-flow with the front-end app (installed and run via `vagrant`), builded the executor project from source with `workflowexecutor\assembly` from sbt-shell as suggested by the docs, and submitted a spark job (again, as per docs), to run the app with the simple json

Unfortunately, I get an exception (stacktrace pasted below):
It seems to me that there is an error in connecting to the Python gateway, which leads me to two questions:

- where does the error come from? What are the exact requirements needed to compile and run the executor app? Because I see no Python in the README, so I guess more maybe is missing
- why do I even need a Python gateway, just for a simple json with no custom code involved? Is there a way in which I can avoid this?

> [INFO ] [2018-05-17 14:12:11,319] [Thread-14]  ai.deepsense.workflowexecutor.executor.PythonExecutionCaretaker - Starting a new PyExecutor process: python C:\Users\SIMONE~1\AppData\Local\Temp\1526559129959-0/pyexecutor/pyexecutor.py --gateway-address 127.0.0.1:53540
[INFO ] [2018-05-17 14:12:39,961] [Thread-15]  ai.deepsense.workflowexecutor.pythongateway.PythonGateway$GatewayEventListener - Gateway server stopped
[INFO ] [2018-05-17 14:12:39,986] [Thread-14]  ai.deepsense.workflowexecutor.executor.PythonExecutionCaretaker - PyExecutor exited with code 1
[INFO ] [2018-05-17 14:12:40,237] [Thread-14]  ai.deepsense.workflowexecutor.executor.PythonExecutionCaretaker - Listening port unavailable, not running PyExecutor
[ERROR] [2018-05-17 14:12:40,239] [ForkJoinPool-1-worker-13]  ai.deepsense.workflowexecutor.executor.WorkflowExecutor$ - Error while processing workflow: Success(WorkflowWithVariables(99aebde7-153e-4635-b637-c72d50266a1b,WorkflowMetadata(batch,1.4.3),DeeplangGraph(Set(Node(939648e4-75d9-bf08-0715-770d68a528c7,ai.deepsense.deeplang.doperations.ReadDatasource@616b4473), Node(fd6fa3e0-0661-a97c-9379-43e26a964861,ai.deepsense.deeplang.doperations.FilterRows@675c6d12)),Set(Edge(Endpoint(939648e4-75d9-bf08-0715-770d68a528c7,0),Endpoint(fd6fa3e0-0661-a97c-9379-43e26a964861,0)))),{"gui":{"name":"mar test","description":"Mar test","nodes":{"939648e4-75d9-bf08-0715-770d68a528c7":{"uiName":"","color":"#00B1EB","coordinates":{"x":7737,"y":8696}},"fd6fa3e0-0661-a97c-9379-43e26a964861":{"uiName":"","color":"#00B1EB","coordinates":{"x":7679,"y":8839}}}},"notebooks":{},"datasources":[{"accessLevel":"writeRead","params":{"name":"Access.Users","libraryFileParams":null,"downloadUri":null,"googleSpreadsheetParams":null,"jdbcParams":{"url":"jdbc:sqlserver://DESKTOP-07H6KGG;database=mar-new;user=simone;password=ciao","driver":"com.microsoft.sqlserver.jdbc.SQLServerDriver","query":null,"table":"Access.Users"},"hdfsParams":null,"externalFileParams":null,"datasourceType":"jdbc","visibility":"privateVisibility"},"creationDateTime":"2018-05-15T16:46:42.880Z","id":"cb168a24-65fb-b2e9-71f7-5590d5eef681","ownerName":"user","ownerId":"00000000-0000-0000-0000-000000000001"}]},Variables()))
[ERROR] [2018-05-17 14:12:40,240] [main]  ai.deepsense.workflowexecutor.executor.WorkflowExecutor$ - Unexpected workflow execution exception
java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2$$anon$4.block(ExecutionContextImpl.scala:48)
	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2.blockOn(ExecutionContextImpl.scala:45)
	at scala.concurrent.Await$.result(package.scala:190)
	at ai.deepsense.workflowexecutor.customcode.CustomCodeEntryPoint$.ai$deepsense$workflowexecutor$customcode$CustomCodeEntryPoint$$getFromPromise(CustomCodeEntryPoint.scala:93)
	at ai.deepsense.workflowexecutor.customcode.CustomCodeEntryPoint.getCodeExecutor(CustomCodeEntryPoint.scala:59)
	at ai.deepsense.workflowexecutor.pythongateway.PythonGateway.codeExecutor(PythonGateway.scala:51)
	at ai.deepsense.workflowexecutor.executor.PythonExecutionCaretaker.waitForPythonExecutor(PythonExecutionCaretaker.scala:57)
	at ai.deepsense.workflowexecutor.executor.PythonExecutionCaretaker.start(PythonExecutionCaretaker.scala:70)
	at ai.deepsense.workflowexecutor.executor.WorkflowExecutor$$anonfun$execute$1.apply(WorkflowExecutor.scala:102)
	at ai.deepsense.workflowexecutor.executor.WorkflowExecutor$$anonfun$execute$1.apply(WorkflowExecutor.scala:67)
	at scala.util.Try$.apply(Try.scala:192)
	at ai.deepsense.workflowexecutor.executor.WorkflowExecutor.execute(WorkflowExecutor.scala:67)
	at ai.deepsense.workflowexecutor.executor.WorkflowExecutor$.ai$deepsense$workflowexecutor$executor$WorkflowExecutor$$executeWorkflow(WorkflowExecutor.scala:298)
	at ai.deepsense.workflowexecutor.executor.WorkflowExecutor$$anonfun$2.apply(WorkflowExecutor.scala:201)
	at ai.deepsense.workflowexecutor.executor.WorkflowExecutor$$anonfun$2.apply(WorkflowExecutor.scala:201)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[INFO ] [2018-05-17 14:12:40,252] [Thread-1]  org.apache.spark.SparkContext - Invoking stop() from shutdown hook

**Comment by jaroslaw-osmanski** [comment]
As noted by you this is connected to Python gateway stopped. The reason isn't clear from logs and might be connected with Windows. What OS are you using? Can you try running your workflow on linux (Ubuntu 14.04) or on Vagrant?

Python executor isn't compiled as it is a python app. It's interpreted in sessionmanager docker.
We don't support partial deployment of Seahorse, so in your case Seahorse without Python isn't possible.

**Comment by jaroslaw-osmanski** [comment]
Closing because no further information was provided
